# Generated by Django 5.2.1 on 2025-05-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_address_employeeaddress_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddress',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='employees.employee'),
        ),
    ]
