# Generated by Django 5.2.1 on 2025-05-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeeaddress_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee'),
        ),
    ]
