# Generated by Django 5.2.1 on 2025-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_user_alter_workschedule_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobile_phone',
            new_name='mobile_phone1',
        ),
        migrations.RenameField(
            model_name='employeeaddress',
            old_name='home',
            new_name='apartment',
        ),
        migrations.AddField(
            model_name='employee',
            name='chair',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='color_hex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_using_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeaddress',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profession',
        ),
        migrations.AlterField(
            model_name='employeeaddress',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeaddress',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='employee', to='employees.profession'),
        ),
    ]
