# Generated by Django 5.2.1 on 2025-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_doctor_appointment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('upcoming_task', 'Upcoming Task'), ('upcoming_visit', 'Upcoming Visit')], default='pending', max_length=30),
        ),
    ]
