# Generated by Django 5.2.1 on 2025-06-03 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_chair_alter_employee_color_hex_and_more'),
        ('patients', '0003_remove_patient_address_remove_patient_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientaddress',
            old_name='home',
            new_name='apartment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='extra_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='future_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_phone1',
            field=models.CharField(default='998995556633', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treated_doctors',
            field=models.ManyToManyField(blank=True, related_name='treated_doctor', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientaddress',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='region',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
